"""Puertos (interfaces) del dominio `products` para desacoplar infraestructura."""

from typing import Protocol

from app.domain.products.entities import ProductData, ProductListFilters, ProductSupplierData, ProductSupplierInput, ProductWriteInput
from app.domain.products.read_models import ProductDeleteResult


class ProductsRepository(Protocol):
    def list_products(self, filters: ProductListFilters) -> list[ProductData]: ...

    def category_exists(self, category_id: str) -> bool: ...

    def create_product(self, payload: ProductWriteInput) -> ProductData: ...

    def get_product(self, product_id: str, include_details: bool) -> ProductData | None: ...

    def update_product(self, product_id: str, payload: ProductWriteInput) -> ProductData | None: ...

    def delete_product(self, product_id: str) -> ProductDeleteResult | None: ...

    def list_product_suppliers(self, product_id: str) -> list[ProductSupplierData]: ...

    def product_exists(self, product_id: str) -> bool: ...

    def supplier_exists(self, supplier_id: str) -> bool: ...

    def upsert_product_supplier(self, product_id: str, payload: ProductSupplierInput) -> ProductSupplierData: ...

    def remove_product_supplier(self, product_id: str, supplier_id: str) -> bool: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...

    def rollback(self) -> None: ...
