"""Puertos (interfaces) del dominio `projects` para desacoplar infraestructura."""

from typing import Protocol

from app.domain.projects.entities import ProjectFilters, ProjectInput
from app.domain.projects.read_models import ProjectMutationResult, ProjectView


class ProjectsRepository(Protocol):
    def list_projects(self, filters: ProjectFilters) -> list[ProjectView]: ...

    def create_project(self, payload: ProjectInput) -> ProjectView: ...

    def get_project(self, project_id: str) -> ProjectView: ...

    def update_project(self, project_id: str, payload: ProjectInput) -> ProjectView: ...

    def delete_project(self, project_id: str) -> ProjectMutationResult: ...

    def client_exists(self, client_id: str) -> bool: ...

    def assigned_user_exists(self, user_id: str) -> bool: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...

    def rollback(self) -> None: ...
