"""init

Revision ID: 2ad775a82a2f
Revises: 
Create Date: 2026-02-21 10:26:54.419860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad775a82a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rutUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('contactName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rutUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entityType', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ipAddress', sa.String(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('performedBy', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performedBy'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplierId', sa.String(), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categoryId', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rentalPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('clientId', sa.String(), nullable=False),
    sa.Column('assignedTo', sa.String(), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('tokenHash', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_tokenHash'), 'refresh_tokens', ['tokenHash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_userId'), 'refresh_tokens', ['userId'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('canView', sa.Boolean(), nullable=False),
    sa.Column('canEdit', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('serialNumber', sa.String(), nullable=True),
    sa.Column('assetTag', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('containerId', sa.String(), nullable=True),
    sa.Column('purchaseDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchasePrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warrantyExpiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['containerId'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_suppliers',
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('supplierId', sa.String(), nullable=False),
    sa.Column('supplierSku', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('isPreferred', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productId', 'supplierId')
    )
    op.create_table('quotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quotationNumber', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validUntil', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('clientId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignedTo', sa.String(), nullable=True),
    sa.Column('dueDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inventoryItemId', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('fromStatus', sa.String(), nullable=True),
    sa.Column('toStatus', sa.String(), nullable=False),
    sa.Column('fromLocation', sa.String(), nullable=True),
    sa.Column('toLocation', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('performedBy', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventoryItemId'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performedBy'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_group_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=False),
    sa.Column('inventoryItemId', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['item_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventoryItemId'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quotationId', sa.String(), nullable=False),
    sa.Column('groupId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['item_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotationId'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quotationId', sa.String(), nullable=False),
    sa.Column('inventoryItemId', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventoryItemId'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotationId'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('epc', sa.String(), nullable=False),
    sa.Column('tid', sa.String(), nullable=True),
    sa.Column('inventoryItemId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('firstSeenAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastSeenAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventoryItemId'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfidTagId', sa.String(), nullable=False),
    sa.Column('readerId', sa.String(), nullable=False),
    sa.Column('readerName', sa.String(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfidTagId'], ['rfid_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfid_detections')
    op.drop_table('rfid_tags')
    op.drop_table('quotation_items')
    op.drop_table('quotation_groups')
    op.drop_table('item_group_items')
    op.drop_table('inventory_movements')
    op.drop_table('tasks')
    op.drop_table('quotations')
    op.drop_table('product_suppliers')
    op.drop_table('inventory_items')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_refresh_tokens_userId'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tokenHash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('projects')
    op.drop_table('products')
    op.drop_table('concepts')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('item_groups')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
